### ISSUE TITLE
Escape analysis

### ISSUE THREAD

**Issue by cinquin** [google/allocation-instrumenter#17]
Am I correct in thinking that the instrumenter reports both on-heap and on-stack allocations? It seems that it has to, given that it's (in part) instrumenting calls to constructors — which should take place irrespective of the kind of allocation.

I ask in part because a bunch of comments in the code mention heap allocation but not on-stack allocation.

Is there a way to modify the instrumenter to only report on-heap allocations, which are the ones that are relevant to garbage collection pressure? (I think the answer is no, unfortunately.) I know one can use the `-XX:+PrintEscapeAnalysis` JVM flag but parsing the output appears rather tedious.

**Comment by jhmanson** [comment]
I'm afraid this is not feasible by using bytecode rewriting; the instrumentation is done prior to the JVM making those decisions.

We are coming back to work on this, and are looking at badgering Oracle for more direct JVM support.  It's probably worth thinking about this use case.

**Comment by cinquin** [comment]
OK, that's what I thought. It might be worth updating the comments in the code that refer to heap allocation.
Thanks for the response.
