### ISSUE TITLE
JDK11 Compilation Error

### ISSUE THREAD

**Issue by anonymousemberxxx** [google/allocation-instrumenter#33]
Hello,

I just wanted to compile the tool (mvn package) with JDK11 and mvn 3.6.1. It seems that it always has the compilation errors:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.680 s
[INFO] Finished at: 2019-12-25T21:13:34-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project java-allocation-instrumenter: Compilation failure: Compilation failure:
[ERROR] /home/bli11/allocation-instrumenter/target/generated-sources/java/com/google/monitoring/runtime/instrumentation/AllocationInstrumenterBootstrap.java:[7,24] cannot find symbol
[ERROR]   symbol:   class Generated
[ERROR]   location: package javax.annotation
[ERROR] /home/bli11/allocation-instrumenter/target/generated-sources/java/com/google/monitoring/runtime/instrumentation/AllocationInstrumenterBootstrap.java:[33,2] cannot find symbol
[ERROR]   symbol: class Generated
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

I have added some dependencies in pom.xml, but it doesn't work? Any suggestions? Thanks a lot!

**Comment by jhmanson** [comment]
Thanks for the report.  Fix is in progress.

**Comment by jhmanson** [comment]
It may take a bit, because a bunch of stuff is broken, code reviews need to happen, another dependent project needs to be updated, and people are still on vacation.

**Comment by jhmanson** [comment]
This should work at head now.  Caveats:

1) The tests don't work in the maven build.  Use -DskipTests.
2) The bazel build's tests work, and the output is smaller.  

In general, I haven't been keeping up the Maven build very well.  You might consider using Bazel instead.

Please let me know if you have any problems!
