### ISSUE TITLE
Will the instrumenter detect allocations made via JNI?

### ISSUE THREAD

**Issue by jatindersangha** [google/allocation-instrumenter#50]
Hi,

Apologies in advance, this is a question rather than an issue - but I couldn't find a forum etc to ask the question, so here goes.

The instrumenter will instrument java code to identify allocations and invoke the appropriate callback.

However, if a java object is allocated from within JNI code - will this also be identified and the sampler callback invoked?

Thanks,
--Jatinder

**Comment by jhmanson** [comment]
Alas, no, it will not.  I am aware of a couple of ways of doing this if you are using an OpenJDK-based Java.

First, you can JVMTI's function interception mechanism to intercept JNI's NewObject methods to record the allocation (and then call back to the real NewObject methods).  This requires you to write a JVMTI agent in native code.  See docs here:

https://docs.oracle.com/en/java/javase/17/docs/specs/jvmti.html#jniIntercept

Alternatively, you can use Hotspot's support for dtrace / systemtap probes.  I don't think this is terribly well documented, but I see a page that describes the general idea here:

https://myaut.github.io/dtrace-stap-book/app/java.html

Depending on what you want to do with the information, there may be other ways of accomplishing it.  For example, if you are sampling allocations, JVMTI lets you do that.

**Comment by jatindersangha** [comment]
Hi, thanks for the response.

I think I'll try and build something suitable for my needs using JVMTI.

Thanks,
--Jatinder
