### ISSUE TITLE
Capture the location where the new object is created

### ISSUE THREAD

**Issue by januslinhc** [google/allocation-instrumenter#56]
Hello,

May I know is there any way to capture the location where the new object is created with the memory allocation sampler (e.g. print the stack trace from a throwable in the constructor of new object)? It will be useful for further investigate.

Thanks!

**Comment by jhmanson** [comment]
I think that comment (from 2008) may have been superseded by a change (from 2009), which uses a ThreadLocal to determine if an allocation is in progress:

https://github.com/google/allocation-instrumenter/blob/master/src/main/java/com/google/monitoring/runtime/instrumentation/AllocationRecorder.java#L162

Probably worth checking, though.
